import LoadingSpinner from "../common/LoadingSpinner";
import ErrorMessage from "../common/ErrorMessage";

const AISignalPanel = ({ signal, confidence, loading, error }) => {
  if (loading) {
    return (
      <div className="bg-gray-800 p-4 rounded-lg">
        <div className="flex items-center justify-center">
          <LoadingSpinner />
          <span className="ml-2 text-gray-400">Loading AI signal...</span>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="bg-gray-800 p-4 rounded-lg">
        <ErrorMessage message={error} />
      </div>
    );
  }

  if (!signal) {
    return (
      <div className="bg-gray-800 p-4 rounded-lg">
        <div className="text-gray-400 text-center">
          No signal data available
        </div>
      </div>
    );
  }

  const getSignalColor = (signal) => {
    switch (signal.toUpperCase()) {
      case 'BUY':
        return 'text-green-400';
      case 'SELL':
        return 'text-red-400';
      case 'HOLD':
        return 'text-yellow-400';
      default:
        return 'text-gray-400';
    }
  };

  const getSignalIcon = (signal) => {
    switch (signal.toUpperCase()) {
      case 'BUY':
        return '▲';
      case 'SELL':
        return '▼';
      case 'HOLD':
        return '●';
      default:
        return '○';
    }
  };

  return (
    <div className="bg-gray-800 p-4 rounded-lg">
      <div className="flex justify-between items-center mb-3">
        <h4 className="text-white font-medium">AI Trading Signal</h4>
        <div className={`font-semibold text-lg ${getSignalColor(signal)}`}>
          {getSignalIcon(signal)} {signal.toUpperCase()}
        </div>
      </div>

      {confidence && (
        <div className="mb-3">
          <div className="flex justify-between items-center text-sm">
            <span className="text-gray-400">Confidence</span>
            <span className="text-white font-medium">{confidence.toFixed(1)}%</span>
          </div>
          <div className="w-full bg-gray-700 rounded-full h-2 mt-1">
            <div
              className={`h-2 rounded-full transition-all duration-300 ${
                confidence >= 70 ? 'bg-green-500' :
                confidence >= 50 ? 'bg-yellow-500' : 'bg-red-500'
              }`}
              style={{ width: `${Math.min(confidence, 100)}%` }}
            ></div>
          </div>
        </div>
      )}

      <div className="text-xs text-gray-500">
        Signal generated by quantitative factors and ML models
      </div>
    </div>
  );
};

export default AISignalPanel;