import LoadingSpinner from "../common/LoadingSpinner";
import ErrorMessage from "../common/ErrorMessage";

/**
 * AISignalPanel — shows the model's BUY/SELL/HOLD signal + confidence bar.
 */
const tone = (s) => {
  const v = String(s || "").toUpperCase();
  if (v === "BUY") return { text: "text-up", bar: "bg-up", icon: "▲" };
  if (v === "SELL") return { text: "text-down", bar: "bg-down", icon: "▼" };
  if (v === "HOLD") return { text: "text-amber-400", bar: "bg-amber-400", icon: "●" };
  return { text: "text-gray-400", bar: "bg-gray-500", icon: "○" };
};

export default function AISignalPanel({ signal, confidence, loading, error }) {
  const wrap = "rounded-xl border border-line/70 bg-ink-900/60 p-4";

  if (loading) {
    return (
      <div className={`${wrap} flex items-center justify-center gap-2`}>
        <LoadingSpinner />
        <span className="text-sm text-gray-400">Loading AI signal…</span>
      </div>
    );
  }
  if (error) {
    return (
      <div className={wrap}>
        <ErrorMessage message={error} />
      </div>
    );
  }
  if (!signal) {
    return <div className={`${wrap} text-center text-sm text-gray-400`}>No signal data available</div>;
  }

  const t = tone(signal);
  const hasConf = typeof confidence === "number" && Number.isFinite(confidence);
  const barColor = !hasConf
    ? "bg-gray-600"
    : confidence >= 70
    ? "bg-up"
    : confidence >= 50
    ? "bg-amber-400"
    : "bg-down";

  return (
    <div className={wrap}>
      <div className="mb-3 flex items-center justify-between">
        <h4 className="text-sm font-medium text-white">AI Trading Signal</h4>
        <div className={`text-lg font-semibold ${t.text}`}>
          {t.icon} {String(signal).toUpperCase()}
        </div>
      </div>

      {hasConf && (
        <div className="mb-3">
          <div className="flex items-center justify-between text-sm">
            <span className="text-gray-400">Confidence</span>
            <span className="tnum font-medium text-white">{confidence.toFixed(1)}%</span>
          </div>
          <div className="mt-1 h-2 w-full overflow-hidden rounded-full bg-ink-700">
            <div
              className={`h-2 rounded-full transition-all duration-300 ${barColor}`}
              style={{ width: `${Math.min(Math.max(confidence, 0), 100)}%` }}
            />
          </div>
        </div>
      )}

      <p className="text-xs text-gray-500">
        Generated by quantitative factors and ML models.
      </p>
    </div>
  );
}
